schema: 
  - ${NEXT_PUBLIC_API_URL:./schema.graphql}:
      headers:
        Authorization: "Bearer ${NEXT_PUBLIC_API_TOKEN}"
documents: src/**/!(*.d).{ts,tsx}

extensions:
  codegen:
    overwrite: true
    schema: 
      - ${NEXT_PUBLIC_API_URL:./schema.graphql}:
          headers:
            Authorization: "Bearer ${NEXT_PUBLIC_API_TOKEN}"
    documents: src/**/!(*.d).{ts,tsx}

    generates:
      schema.graphql:
        plugins:
          - schema-ast

      src/types/graphql.generated.ts:
        plugins:
          - typescript
          - typescript-operations
        config:
          useTypeImports: true
          constEnums: true
          scalars:
            RichTextAST: "~/types/RichTextAST#RichTextAST"
            Portfolio_RichTextAST: "~/types/RichTextAST#RichTextAST"