fragment SimpleProject on Project {
  id
  title
  slug
  image {
    id
    url
  }
  framework
  createdAt
}

query Project($slug: String!) {
  project(where: { slug: $slug }) {
    ...SimpleProject
    description {
      raw
      text
    }
    sourceCode
    preview
    tags {
      id
      name
      slug
    }
  }
}

query Preview($slug: String!) {
  project(where: { slug: $slug }) {
    id
    preview
  }
}

query Projects(
  $after: String
  $before: String
  $first: Int
  $last: Int
  $skip: Int
  $where: ProjectWhereInput
) {
  projects(
    after: $after
    before: $before
    first: $first
    last: $last
    skip: $skip
    where: $where,
    orderBy: createdAt_DESC
  ) {
    ...SimpleProject
  }
}
